workflows:
  my-workflow:
    name: iOS Build (Once Zip, Sonra IPA)
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: GoogleService-Info.plist'i Xcode'a Ekle (Windows Fix)
        script: |
          # Bu betik, Windows'ta eklenen dosyayi Xcode projesine tanitir
          gem install xcodeproj
          ruby -e '
            require "xcodeproj"
            project_path = "ios/Runner.xcodeproj"
            project = Xcodeproj::Project.open(project_path)
            file_name = "GoogleService-Info.plist"
            # Dosyanin zaten ekli olup olmadigini kontrol et
            unless project.main_group["Runner"].files.any? { |f| f.path == file_name }
              file_ref = project.main_group["Runner"].new_file(file_name)
              project.targets.first.add_resources([file_ref])
              project.save
              puts "Dosya basariyla Xcode projesine eklendi!"
            else
              puts "Dosya zaten projede ekli."
            end
          '

      - name: Paketleri Getir
        script: |
          flutter pub get
          # Podfile'i onceden garantiye alalim (eger yoksa)
          find . -name "Podfile" -execdir pod install \;

      # --- SIRALAMA DEGISTI: ONCE ZIP ---
      - name: 1. Web Simulator icin Build Al (.zip)
        script: |
          flutter build ios --debug --simulator
          cd build/ios/iphonesimulator
          # Simülatör build'ini ziple
          zip -r Runner.zip Runner.app

      # --- SONRA IPA ---
      - name: 2. Telefon icin Build Al (.ipa)
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphonesimulator/*.zip
      - flutter_drive.log
