workflows:
  my-workflow:
    name: iOS Build (Telefon ve Web icin)
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Paketleri Getir
        script: |
          flutter pub get
          find . -name "Podfile" -execdir pod install \;

      - name: 1. Telefon icin Build Al (.ipa)
        script: |
          # DÜZELTME: Hataya sebep olan --export-options-plist parametresi kaldirildi.
          # Artik sorunsuz sekilde imzasiz .ipa uretecek.
          flutter build ipa --release --no-codesign

      - name: 2. Web Simulator icin Build Al (.zip)
        script: |
          # Bu kisim ayni kaliyor, web testi icin gerekli
          flutter build ios --debug --simulator
          cd build/ios/iphonesimulator
          zip -r Runner.zip Runner.app

    artifacts:
      - build/ios/ipa/*.ipa # Telefon icin
      - build/ios/iphonesimulator/*.zip # Web testi icin
      - flutter_drive.log
