workflows:
  my-workflow:
    name: iOS Build (Once Zip, Sonra IPA)
    instance_type: mac_mini_m1
    environment:
      groups:
        # Define key id, issuer id, private key (.p8) file
        # Generated at https://appstoreconnect.apple.com/access/integrations/api
        # and stored in Codemagic' env variables tab all under same group name
        - appstore_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.kgs.kgsyksDestek"  # same bundleid from appstore
    scripts:
      - name: Fetch signing files from App Store Connect
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --certificate-key=@env:CERTIFICATE_PRIVATE_KEY
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Configure Xcode signing
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
          # Podfile'i onceden garantiye alalim (eger yoksa)
          find . -name "Podfile" -execdir pod install \;

      # --- SIRALAMA DEGISTI: ONCE ZIP ---
      - name: 1. Web Simulator icin Build Al (.zip)
        script: |
          flutter build ios --debug --simulator
          cd build/ios/iphonesimulator
          # Simülatör build'ini ziple
          zip -r Runner.zip Runner.app

      # --- SONRA IPA ---
      - name: 2. Telefon icin Build Al (.ipa)
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
