workflows:
  my-workflow:
    name: iOS Build (Telefon ve Web icin)
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Paketleri Getir
        script: |
          flutter pub get
          find . -name "Podfile" -execdir pod install \;

      - name: 1. Telefon icin Build Al (.ipa)
        script: |
          # Bu komut gercek iPhone'a yuklenecek dosyayi uretir
          flutter build ipa --release --no-codesign --export-options-plist=$FCI_BUILD_DIR/ios/Runner/ExportOptions.plist
          # Not: Sertifika yoksa --no-codesign ile imzasiz alirsiniz.

      - name: 2. Web Simulator icin Build Al (.zip)
        script: |
          # Bu komut Appetize.io gibi sitelerde calisacak dosyayi uretir
          flutter build ios --debug --simulator
          cd build/ios/iphonesimulator
          zip -r Runner.zip Runner.app

    artifacts:
      - build/ios/ipa/*.ipa # Telefon icin
      - build/ios/iphonesimulator/*.zip # Web testi icin
      - flutter_drive.log
