workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      # exact ref name you gave your key in Codemagic and appstoreconnect 
      app_store_connect: Codemagic API Key
    environment:
      groups:
        # Define key id, issuer id, private key (.p8) file
        # Generated at https://appstoreconnect.apple.com/access/integrations/api
        # and stored in Codemagic' env variables tab all under same group name
        - appstore_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.kgs.kgsyksDestek"  # same bundleid from appstore
    scripts:
      - name: Fetch signing files from App Store Connect
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --certificate-key=@env:CERTIFICATE_PRIVATE_KEY
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Configure Xcode signing
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Build iOS app ipa for release
        # Builds the .ipa using the export options generated by the fetch-signing-files step
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
