// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWHGqtK-jtmuwUiP4epF15ERijvucwSt0',
    appId: '1:9542571085:web:085826d7c593408727b804',
    messagingSenderId: '9542571085',
    projectId: 'kgsyks-destek-b7645',
    authDomain: 'kgsyks-destek-b7645.firebaseapp.com',
    storageBucket: 'kgsyks-destek-b7645.firebasestorage.app',
    measurementId: 'G-8QH4TYJKKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGRM_t810paRT0NsAZsSkGECauESfeliU',
    appId: '1:9542571085:android:c8a4b613637ad04727b804',
    messagingSenderId: '9542571085',
    projectId: 'kgsyks-destek-b7645',
    storageBucket: 'kgsyks-destek-b7645.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYND-jVuCP38-al6mSfU09K3s03ZxFBSc',
    appId: '1:9542571085:ios:bc3a89c04c2ea34027b804',
    messagingSenderId: '9542571085',
    projectId: 'kgsyks-destek-b7645',
    storageBucket: 'kgsyks-destek-b7645.firebasestorage.app',
    iosBundleId: 'com.kgs.kgsyksDestek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYND-jVuCP38-al6mSfU09K3s03ZxFBSc',
    appId: '1:9542571085:ios:bc3a89c04c2ea34027b804',
    messagingSenderId: '9542571085',
    projectId: 'kgsyks-destek-b7645',
    storageBucket: 'kgsyks-destek-b7645.firebasestorage.app',
    iosBundleId: 'com.kgs.kgsyksDestek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWHGqtK-jtmuwUiP4epF15ERijvucwSt0',
    appId: '1:9542571085:web:bf0d2d4aca3658e727b804',
    messagingSenderId: '9542571085',
    projectId: 'kgsyks-destek-b7645',
    authDomain: 'kgsyks-destek-b7645.firebaseapp.com',
    storageBucket: 'kgsyks-destek-b7645.firebasestorage.app',
    measurementId: 'G-KT3CG6B433',
  );
}