List<String> konuListMatematik = [
  "Temel Kavramlar",
  "Sayı Basamakları",
  "Bölme Bölünebilme",
  "EBOB-EKOK",
  "Rasyonel Sayılar",
  "Basit Eşitsizlikler",
  "Mutlak Değer",
  "Üslü Sayılar",
  "Köklü Sayılar",
  "Çarpanlara Ayırma",
  "Oran Orantı",
  "Denklem Çözme",
  "Problemler",
  "Kümeler",
  "Kartezyen Çarpım",
  "Mantık",
  "Fonksiyonlar",
  "Polinomlar",
  "Permütasyon Kombinasyon",
  "Binom Olasılık",
  "İstatistik",
  "Karmaşık Sayılar",
  "2.Dereceden Denklemler",
  "2.Dereceden Eşitsizlikler",
  "Parabol",
  "Trigonometri",
  "Logaritma",
  "Diziler",
  "Limit",
  "Türev",
  "İntegral",
  "İstatistik",
];

List<String> konuListTurkce = [
  "Sözcükte Anlam",
  "Yazım Kuralları",
  "Noktalama İşaretleri",
  "Sözcük Yapısı",
  "İsimler",
  "Zamirler",
  "Sıfatlar",
  "Zarflar",
  "Edat Bağlaç Ünlem",
  "Fiiller",
  "Sözcük Grupları",
  "Deyim Atasözü",
  "Cümlenin Ögeleri",
  "Cümle Türleri",
  "Anlatım Bozukluğu",
  "Cümlede Anlam",
  "Cümle Yorumu",
  "Anlatım Teknikleri",
  "Paragraf Konu Ana Düşünce",
  "Paragrafta Yapı",
  "Paragraf Yardımcı Düşünceler",
  "Ses Bilgisi",
];

List<String> konuListGeometri = [
  "Temel Kavramlar",
  "Doğruda Açılar",
  "Üçgende Açılar",
  "Özel Üçgenler",
  "Açıortay",
  "KenarOrtay",
  "Üçgende Alan",
  "Üçgende Benzerlik",
  "Açı Kenar Bağıntıları",
  "Çokgenler",
  "Özel Dörtgenler",
  "Çember ve Daire",
  "Analitik Geometri",
  "Katı Cisimler",
  "Uzay Geometri",
  "Çemberin Analitiği",
];

List<String> konuListFizik = [
  "Fizik Bilimine Giriş",
  "Madde ve Özellikleri",
  "Kaldırma Kuvveti",
  "Basınç",
  "Isı Sıcaklık Genleşme",
  "Hareket",
  "Dinamik",
  "İş Güç Enerji",
  "Elektrostatik",
  "Elektrik Akımı",
  "Optik",
  "Manyetizma",
  "Dalgalar",
  "Vektörler",
  "Kuvvet Tork Denge",
  "Kütle Merkezi",
  "Basit Makineler",
  "Hareket",
  "Newton Yasaları",
  "Atışlar",
  "İtme Momentum",
  "Elektrik Alan",
  "Paralel Levhalar",
  "Sığalar",
  "Manyetik Alan",
  "İndüksiyon Alternatif Akım",
  "Transformatörler",
  "Çembersel Hareket",
  "Kütle Çekim ve Kepler",
  "Basit Harmonik Hareket",
  "Dalga Mekaniği",
  "Atom Modelleri",
  "Büyük Patlama ve Radyoaktivite",
  "Modern Fizik",
  "Modern Fizik Teknoloji Uygulamaları",
];

List<String> konuListKimya = [
  "Kimya Bilimi",
  "Atom Yapısı",
  "Periyodik Tablo",
  "Maddenin Halleri",
  "Kimyasal Türler Arası Etkileşim",
  "Kimyasal Hesaplamalar",
  "Kimya Temel Kanunları",
  "Asit Baz Tuz",
  "Karışımlar",
  "Kimya Her Yerde",
  "Modern Atom Teorisi",
  "Gazlar",
  "Çözeltiler",
  "Kimyasal Tepkimelerde Enerji",
  "Kimyasal Tepkimelerde Hız",
  "Kimyasal Tepkimelerde Denge",
  "Asit Baz Dengesi",
  "Çözünürlük Dengesi",
  "Kimya ve Elektrik",
  "Organik Kimya",
];

List<String> konuListBiyoloji = [
  "Canlıların Ortak Özellikleri",
  "Canlıların Temel Bileşenleri",
  "Hücre ve Organelleri",
  "Madde Geçişleri",
  "Canlıların Sınıflandırılması",
  "Hücre Bölünmeleri",
  "Üreme",
  "Kalıtım",
  "Ekosistem Ekolojisi",
  "Bitkiler Biyolojisi",
  "Sinir Sistemi",
  "Endokrin Sistem",
  "Duyu Organları",
  "Destek ve Hareket Sistemi",
  "Sindirim Sistemi",
  "Dolaşım ve Bağışıklık Sistemi",
  "Solunum Sistemi",
  "Boşaltım Sistemi",
  "Üriner Sistem",
  "Üreme Sistemi ve Embriyonik Gelişim",
  "Komünite ve Popülasyon Ekolojisi",
  "Mükleik Asitler",
  "Genetik Şifre",
  "Protein Sentezi",
  "Canlılık ve Enerji",
  "Fotosentez Kemosentez",
  "Hücresel Solunum",
  "Bitki Biyolojisi",
  "Canlılar ve Çevre",
];

List<String> konuListDin = [
  "Bilgi ve İnanç",
  "İbadetler",
  "Ahlak ve Değerler",
  "Hz.Muhammed (s.a.v)",
  "Vahiy ve Akıl",
  "İslam Düşüncesi Yorumlar",
  "Mezhepler",
  "Din Kültür Medeniyet",
];

List<String> konuListFelsefe = [
  "Felsefe Alanı",
  "Bilgi Felsefesi",
  "Bilim Felsefesi",
  "Varlık Felsefesi",
  "Ahlak Felsefesi",
  "Siyaset Felsefesi",
  "Din Felsefesi",
  "Sanat Felsefesi",
];

List<String> konuListCografya = [
  "Doğa ve insan",
  "Dünya Şekli Hareketleri",
  "Coğrafi Konum",
  "Harita Bilgisi",
  "Atmosfer Sıcaklık",
  "İklim Bilgisi",
  "İç Dış Kuvvetler",
  "Nüfus Yerleşme",
  "Türkiye Yer Şekilleri",
  "Ekonomik Faaliyetler",
  "Bölgeler",
  "Uluslararası Ulaşım",
  "Doğal Afetler",
];

List<String> konuListTarih = [
  "Tarih Bilimine Giriş",
  "İlk Türk Devletleri",
  "İslam Tarihi",
  "Türk İslam Tarihi",
  "Osmanlı Kuruluşu",
  "Osmanlı Yükseliş Dönemi",
  "Yeniçağ Avrupası",
  "19.yy Osmanlısı",
  "Osmanlı Kültür ve Medeniyeti",
  "20.yy Osmanlısı",
  "1.Dünya Savaşı",
  "Kurtuluş Savaşı",
  "Mondros İşgaller ve Cemiyetler",
  "TBMM Dönemi",
  "Atatürk İlke İnk.ları",
  "Dış Politika",
];

final List<String> dersler = [
  'Türkçe',
  'Matematik',
  'Geometri',
  'Fizik',
  'Kimya',
  'Biyoloji',
  'Tarih',
  'Coğrafya',
  'Din Kültürü',
  'Felsefe',
];

// Mevcut ders ve konu listelerini sınıfın dışına tanımlayın
final List<String> dkonuListeleri = [
  'Türkçe',
  'Matematik',
  'Geometri',
  'Fizik',
  'Kimya',
  'Biyoloji',
  'Tarih',
  'Coğrafya',
  'Din Kültürü',
  'Felsefe',
];

final Map<String, List<String>> konuListeleri = {
  'Türkçe': [
    "Sözcükte Anlam",
    "Yazım Kuralları",
    "Noktalama İşaretleri",
    "Sözcük Yapısı",
    "İsimler",
    "Zamirler",
    "Sıfatlar",
    "Zarflar",
    "Edat Bağlaç Ünlem",
    "Fiiller",
    "Sözcük Grupları",
    "Deyim Atasözü",
    "Cümlenin Ögeleri",
    "Cümle Türleri",
    "Anlatım Bozukluğu",
    "Cümlede Anlam",
    "Cümle Yorumu",
    "Anlatım Teknikleri",
    "Paragraf Konu Ana Düşünce",
    "Paragrafta Yapı",
    "Paragraf Yardımcı Düşünceler",
    "Ses Bilgisi",
  ],
  'Matematik': [
    "Temel Kavramlar",
    "Sayı Basamakları",
    "Bölme Bölünebilme",
    "EBOB-EKOK",
    "Rasyonel Sayılar",
    "Basit Eşitsizlikler",
    "Mutlak Değer",
    "Üslü Sayılar",
    "Köklü Sayılar",
    "Çarpanlara Ayırma",
    "Oran Orantı",
    "Denklem Çözme",
    "Problemler",
    "Kümeler",
    "Kartezyen Çarpım",
    "Mantık",
    "Fonksiyonlar",
    "Polinomlar",
    "Permütasyon Kombinasyon",
    "Binom Olasılık",
    "İstatistik",
    "Karmaşık Sayılar",
    "2.Dereceden Denklemler",
    "2.Dereceden Eşitsizlikler",
    "Parabol",
    "Trigonometri",
    "Logaritma",
    "Diziler",
    "Limit",
    "Türev",
    "İntegral",
    "İstatistik",
  ],
  'Geometri': [
    "Temel Kavramlar",
    "Doğruda Açılar",
    "Üçgende Açılar",
    "Özel Üçgenler",
    "Açıortay",
    "Kenarortay",
    "Üçgende Alan",
    "Üçgende Benzerlik",
    "Açı Kenar Bağıntıları",
    "Çokgenler",
    "Özel Dörtgenler",
    "Çember ve Daire",
    "Analitik Geometri",
    "Katı Cisimler",
    "Uzay Geometri",
    "Çemberin Analitiği",
  ],
  'Fizik': [
    "Fizik Bilimine Giriş",
    "Madde ve Özellikleri",
    "Kaldırma Kuvveti",
    "Basınç",
    "Isı Sıcaklık Genleşme",
    "Hareket",
    "Dinamik",
    "İş Güç Enerji",
    "Elektrostatik",
    "Elektrik Akımı",
    "Optik",
    "Manyetizma",
    "Dalgalar",
    "Vektörler",
    "Kuvvet Tork Denge",
    "Kütle Merkezi",
    "Basit Makineler",
    "Hareket",
    "Newton Yasaları",
    "Atışlar",
    "İtme Momentum",
    "Elektrik Alan",
    "Paralel Levhalar",
    "Sığalar",
    "Manyetik Alan",
    "İndüksiyon Alternatif Akım",
    "Transformatörler",
    "Çembersel Hareket",
    "Kütle Çekim ve Kepler",
    "Basit Harmonik Hareket",
    "Dalga Mekaniği",
    "Atom Modelleri",
    "Büyük Patlama ve Radyoaktivite",
    "Modern Fizik",
    "Modern Fizik Teknoloji Uygulamaları",
  ],
  'Kimya': [
    "Kimya Bilimi",
    "Atom Yapısı",
    "Periyodik Tablo",
    "Maddenin Halleri",
    "Kimyasal Türler Arası Etkileşim",
    "Kimyasal Hesaplamalar",
    "Kimya Temel Kanunları",
    "Asit Baz Tuz",
    "Karışımlar",
    "Kimya Her Yerde",
    "Modern Atom Teorisi",
    "Gazlar",
    "Çözeltiler",
    "Kimyasal Tepkimelerde Enerji",
    "Kimyasal Tepkimelerde Hız",
    "Kimyasal Tepkimelerde Denge",
    "Asit Baz Dengesi",
    "Çözünürlük Dengesi",
    "Kimya ve Elektrik",
    "Organik Kimya",
  ],
  'Biyoloji': [
    "Canlıların Ortak Özellikleri",
    "Canlıların Temel Bileşenleri",
    "Hücre ve Organelleri",
    "Madde Geçişleri",
    "Canlıların Sınıflandırılması",
    "Hücre Bölünmeleri",
    "Üreme",
    "Kalıtım",
    "Ekosistem Ekolojisi",
    "Bitkiler Biyolojisi",
    "Sinir Sistemi",
    "Endokrin Sistem",
    "Duyu Organları",
    "Destek ve Hareket Sistemi",
    "Sindirim Sistemi",
    "Dolaşım ve Bağışıklık Sistemi",
    "Solunum Sistemi",
    "Boşaltım Sistemi",
    "Üriner Sistem",
    "Üreme Sistemi ve Embriyonik Gelişim",
    "Kominite ve Popülasyon Ekolojisi",
    "Nükleik Asitler",
    "Genetik Şifre",
    "Protein Sentezi",
    "Canlılık ve Enerji",
    "Fotosentez Kemosentez",
    "Hücresel Solunum",
    "Bitki Biyolojisi",
    "Canlılar ve Çevre",
  ],
  'Din Kültürü': [
    "Bilgi ve İnanç",
    "İbadetler",
    "Ahlak ve Değerler",
    "Hz.Muhammed (s.a.v)",
    "Vahiy ve Akıl",
    "İslam Düşüncesi Yorumlar",
    "Mezhepler",
    "Din Kültür Medeniyet",
  ],
  'Felsefe': [
    "Felsefe Alani",
    "Bilgi Felsefesi",
    "Bilim Felsefesi",
    "Varlık Felsefesi",
    "Ahlak Felsefesi",
    "Siyaset Felsefesi",
    "Din Felsefesi",
    "Sanat Felsefesi",
  ],
  'Coğrafya': [
    "Doğa ve İnsan",
    "Dünya Şekli Hareketleri",
    "Coğrafi Konum",
    "Harita Bilgisi",
    "Atmosfer Sıcaklık",
    "İklim Bilgisi",
    "İç Dış Kuvvetler",
    "Nüfus Yerleşme",
    "Türkiye Yer Şekilleri",
    "Ekonomik Faaliyetler",
    "Bölgeler",
    "Uluslararası Ulaşım",
    "Doğal Afetler",
  ],
  'Tarih': [
    "Tarih Bilimine Giriş",
    "İlk Türk Devletleri",
    "İslam Tarihi",
    "Türk İslam Tarihi",
    "Osmanlı Kuruluşu",
    "Osmanlı Yükseliş Dönemi",
    "Yeniçağ Avrupası",
    "19.yy Osmanlısı",
    "Osmanlı Kültür ve Medeniyeti",
    "20.yy Osmanlısı",
    "1.Dünya Savaşı",
    "Kurtuluş Savaşı",
    "Mondros İşgaller ve Cemiyetler",
    "TBMM Dönemi",
    "Atatürk İlke İnk.ları",
    "Dış Politika",
  ],
};

final List<String> hataNedeni = [
  'Dikkat Hatası',
  'Yanlış İşaretleme',
  'Süre Sıkıntısı',
  'Bilgi Eksikliği',
  'Pratik Yetersizliği',
];

final List<String> durum = ['Öğrenilecek', 'Beklemede', 'Öğrenildi'];

List<String> filterKonular = [];

void setFilterKonBasedOnX(int x) {
  switch (x) {
    case 0:
      filterKonular = konuListTurkce;
      break;
    case 1:
      filterKonular = konuListMatematik;
      break;
    case 2:
      filterKonular = konuListGeometri;
      break;
    case 3:
      filterKonular = konuListFizik;
      break;
    case 4:
      filterKonular = konuListKimya;
      break;
    case 5:
      filterKonular = konuListBiyoloji;
      break;
    case 6:
      filterKonular = konuListTarih;
      break;
    case 7:
      filterKonular = konuListCografya;
      break;
    case 8:
      filterKonular = konuListDin;
      break;
    case 9:
      filterKonular = konuListFelsefe;
      break;
    default:
      filterKonular = []; // Varsayılan değer
      break;
  }
}

final konularMap = {
  0: konuListTurkce,
  1: konuListMatematik,
  2: konuListGeometri,
  3: konuListFizik,
  4: konuListKimya,
  5: konuListBiyoloji,
  6: konuListTarih,
  7: konuListCografya,
  8: konuListDin,
  9: konuListFelsefe,
};
// Kullanımı:
// setFilterKonBasedOnX(x);
// ... diğer listelerin altında

final Map<String, List<String>> konuMap = {
  'Türkçe': konuListTurkce,
  'Matematik': konuListMatematik,
  'Geometri': konuListGeometri,
  'Fizik': konuListFizik,
  'Kimya': konuListKimya,
  'Biyoloji': konuListBiyoloji,
  'Tarih': konuListTarih,
  'Coğrafya': konuListCografya,
  // 'dersler' listesindeki 'Din Kültürü' ile 'konuListDin'i eşleştiriyoruz.
  'Din Kültürü': konuListDin,
  'Felsefe': konuListFelsefe,
};
// Kullanımı:
// global filter_kon = getFilteredKonuList(x);
